apps/logreg_app/urls.py

# urlpatterns = [ 
#    url(r'^$', index, name = 'my_index'), 
# ]

from django.conf.urls import url, include
from django.contrib import admin
from . import views           # This line is new!

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^create$', views.create, name = "create"), #in views need to have a route with the same name
    url(r'^success$', views.success, name = 'success'), # routing, now routing to success definition. make a new success def on views page
    url(r'^login$', views.login, name = 'login'),
    url(r'^logout$', views.logout, name = 'logout')


    # url(r'^user/(?P<user_id>\d+)/update$', views.update, name = 'update'),
    # url(r'^user/(?P<user_id>\d+)/delete$', views.delete, name = 'delete')
]

logreg/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.logreg_app.urls', namespace='logreg_app')),
]

apps/logreg_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import re
import bcrypt
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
NAME_REGEX = re.compile(r'^[A-Za-z]\w+$')


#did email, didn't do name

# Create your models here.

class BlogManager(models.Manager):
    def reg_validator(self, postData):
        errors = {}
        if len(postData["firstname"]) < 2:
            errors["firstname"] = "first name should be more than 1 character"
            # was name instead of first name length
        if len(postData["lastname"]) < 2:
            errors["lastname"] = "last name should be more than 1 character"
        if len(postData['password']) < 8:
            errors["password"] = "password should be more than 8 character"
        if not re.match(EMAIL_REGEX, postData['emailreg']):
            errors["emailreg"] = ("invalid email")
        if not re.match(NAME_REGEX, postData['firstname']):
            errors["firstname"] = ("invalid first name")
        if not re.match(NAME_REGEX, postData['lastname']):
            errors["lastname"] = ("invalid last name")
        if User.objects.filter(email = postData ['emailreg']).exists():
            errors ['emailreg'] = "email already registered"
        
        return errors
        try:
            User.objects.get(email = postData['emailreg'])
            errors['emailreg'] = "The email is already taken"
        except:
            pass
        return
    def log_validator(self, postData): #need to finish
        errors = {}
        user = User.objects.get(email=postData['emaillog']) # models needs to be =postData, no request, because passing in variable of postdata
        #hashcheck = None python not needed?
        if len(postData['password']) < 8:
            errors["length"] = "password name should be more than 8 character"
            # was name instead of first name length
        if len(User.objects.filter(email = postData['emaillog'])) < 0:
            correct_user = User.objects.filter(email = postData["emaillog"])
        hash1 = bcrypt.checkpw(postData['password'].encode('utf8'), user.password.encode('utf8'))
        if hash1 == False:
            errors ['password'] = "Wrong password"
           # errors["email"] = "Blog name should be more than 1 character"
        # if type
        # if len(postData['desc']) < 10:
            # errors["desc"] = "Blog desc should be more than 10 characters"
        return errors

    # if (request.method == "POST")
    #     try:
    #         user = User.objects.get(email=rquest.POST['email'])
    # if(bcrypt.checkpw(request.POST['password'].encode('utf8'), User.password.encode('utf8'))):
    #     request.session['firstname'] = user.firstname
    #     request.session['firstname'] = user.firstname
    #     request.session['email'] = POST['email']
    #     request.session['id'] = user.id
    #     request.session['is-logged-in'] = True
    # else:
    #     messages.error(rquest, "wrong pass")
    #     return redirect("/")
    # else:
    #      return redirect("/")

class User(models.Model):
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    # confirm = models.CharField(max_length=255) #not needed cause only need to save password
    createdat = models.DateTimeField(auto_now_add = True)
    updatedat = models.DateTimeField(auto_now = True)
    objects = BlogManager()
    # age = models.IntegerField(default=70)
    # desc = models.TextField()


apps/logreg_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from time import gmtime, strftime
from django.utils.crypto import get_random_string
from models import User
import bcrypt
# needed to import User object from models file


def index(request):
    response = "Hello, I am your first request!"
    users = User.objects.all()
    context = {
        'users': users
    }
  # return HttpResponse(response)
    return render(request, 'logreg_app/index.html', context)



def create(request):
    errors = User.objects.reg_validator(request.POST)
    if len (errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('/')

    else:
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        email = request.POST['emailreg']
        password = request.POST['password']
        confirm = request.POST['confirm']
        hashed = bcrypt.hashpw(password.encode('utf8'), bcrypt.gensalt())           
        person = User.objects.create(firstname=firstname, lastname=lastname, email=email, password=hashed)#need to pass in hashed password into database
        request.session["id"] = person.id
        person.save()
        print "registrant was created"
        return redirect("/success") # do not render to POST, could get lost in loop
    #now redirct to route that handles sucess page 
    # return redirect('/')

def login(request):
    errors = User.objects.log_validator(request.POST)
    user = User.objects.get(email=request.POST['emaillog'])
    if len (errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect( "/")
    else:
        bcrypt.checkpw('password'.encode('utf8'), user.password.encode('utf8'))
        request.session['id'] = user.id

        return redirect( "/success")
        # changed to redirect because 
    #errors = Users.objects.login_validator(request.POST)
    #password = request.post['password']

def success(request): #request is default parameter
    users = User.objects.all()
    context = {
        'users': User.objects.get(id=request.session['id'])
    }
    
    return render (request, "logreg_app/success.html", context) 

def logout(request):
    request.session.clear()
    return redirect('/')


apps/logreg_app/templates/logreg_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login & Registration</title>
</head>
<body>
    <h1>Registration</h1> 
    <div>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                   {{ message }}
                </li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    <div>
    <!-- with namespace and url you don't need to type in ........have to use *brace brace percent whatever precent brace brace to use -->
        <form action= "{% url 'logreg_app:create' %}" method="POST"> <!--format is as shown "<insert brace>% url 'users:logout' %<insert brace>"           big url : little url n due to namespace convention-->
                {% csrf_token %}
                First name:<br>
                <input type="text" name="firstname" placeholder="First Name"> <!-- need? value=""-->
                <br>
                Last name:<br>
                <input type="text" name="lastname" placeholder="Last Name">
                <br>
                Email:<br>
                <input type="email" name="emailreg" placeholder="Email">
                <br>
                Password:<br>
                <input type="password" name="password" placeholder="Password">
                <br>
                Password Confirm:<br>
                <input type="password" name="confirm" placeholder="Pass Confirm">
                <br>
                <input type="submit" value="Register">
        </form>    
    </div>
    <h1>Login<h2>
        <!-- <div>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                   {{ message }}
                </li>
                {% endfor %}
            </ul>
            {% endif %}
        </div> -->
            <form action="{% url 'logreg_app:login' %}" method="POST">
                {% csrf_token %} 
                Email:<br>
                <input type="email" name="emaillog" placeholder="Email">
                <br>
                Password:<br>
                <input type="password" name="password" placeholder="Password">
                <br>
                
                <input type="submit" value="Login">
            </form> 

</body>
</html>

apps/logreg_app/templates/logreg_app/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login & Registration</title>
</head>
<body>
    <h1>Success, Welcome {{ users.firstname}}</h1>
    <div class="logout">
        <form action="logout" method="POST">
            {% csrf_token %}
            <input type="submit" name="logout" value="logout">
        </form>
       Successfully registered or logged in!!  
    </div>

</body>
</html>